Use mojo.UI.splitText
Typefounding/underlineStrikethrough pull request #22
Opened 2023-11-20 21:40 UTC by colinmford

Fixes #21 and #17 

Replaces a `GN2UV` lookup with the `mojo.UI.splitText` method to better match the experience users are used to in SpaceCenter. Allows for unicode glyphs and /s/l/a/s/h/e/d text, and if the glyph is still not found it'll just ignore it in the merzView instead of trying to display it and getting an error.

2023-11-22 00:31 UTC, colinmford commented
@ryanbugden or @benkiel, just need a review when you get a minute

2023-11-22 01:50 UTC, ryanbugden commented
@colinmford thanks Colin! I'm out but can review next week at the earliest

2023-11-27 15:18 UTC, ryanbugden commented
@colinmford Quickly tested, and it looks good to me! I did notice another, unrelated UPM issue in the process though (just posted, in case you're curious).

2023-11-27 16:27 UTC, ryanbugden commented
@benkiel I'm happy to handle this and https://github.com/Typefounding/underlineStrikethrough/issues/23 if you'd like to share write access!

2023-11-28 01:22 UTC, benkiel commented
@colinmford did you see my review above?

2023-11-28 01:26 UTC, benkiel requested changes

2023-11-28 01:26 UTC, benkiel commented on Underline Strikethrough.roboFontExt/lib/Underline StrikeThrough.py
> +                    # gName = getKey(ord(char), GN2UV)
Why comment out?

2023-11-28 01:26 UTC, benkiel commented on Underline Strikethrough.roboFontExt/lib/Underline StrikeThrough.py
> +                    # gName = getKey(ord(char), GN2UV)
aka, shouldn't this line just be deleted?

2023-11-28 01:37 UTC, colinmford commented on Underline Strikethrough.roboFontExt/lib/Underline StrikeThrough.py
> +                    # gName = getKey(ord(char), GN2UV)
Done

2023-11-28 01:37 UTC, colinmford commented
@benkiel Cool, made the edits

2023-11-28 03:22 UTC, ryanbugden commented
Thanks both, will go ahead and merge this!

2023-11-28 03:22 UTC, merged